version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    command: bin/rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    depends_on:
      - db
      - redis
    env_file:
      - .env.development
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app_network

  sidekiq:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    command: bundle exec sidekiq -e development -C config/sidekiq.yml
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    depends_on:
      - db
      - redis
    env_file:
      - .env.development
    environment:
      RAILS_ENV: development
    networks:
      - app_network

volumes:
  pg_data:
  redis_data:
  gem_cache:

networks:
  app_network:
