const states = [{ nameShort: 'AC', name: 'Acre' },
                { nameShort: 'AL', name: 'Alagoas' },
                { nameShort: 'AP', name: 'Amapá' },
                { nameShort: 'AM', name: 'Amazonas' },
                { nameShort: 'BA', name: 'Bahia' },
                { nameShort: 'CE', name: 'Ceará' },
                { nameShort: 'DF', name: 'Distrito Federal' },
                { nameShort: 'ES', name: 'Espírito Santo' },
                { nameShort: 'GO', name: 'Goías' },
                { nameShort: 'MA', name: 'Maranhão' },
                { nameShort: 'MT', name: 'Mato Grosso' },
                { nameShort: 'MS', name: 'Mato Grosso do Sul' },
                { nameShort: 'MG', name: 'Minas Gerais' },
                { nameShort: 'PA', name: 'Pará' },
                { nameShort: 'PB', name: 'Paraíba' },
                { nameShort: 'PR', name: 'Paraná' },
                { nameShort: 'PE', name: 'Pernambuco' },
                { nameShort: 'PI', name: 'Piauí' },
                { nameShort: 'RJ', name: 'Rio de Janeiro' },
                { nameShort: 'RN', name: 'Rio Grande do Norte' },
                { nameShort: 'RS', name: 'Rio Grande do Sul' },
                { nameShort: 'RO', name: 'Rondônia' },
                { nameShort: 'RR', name: 'Roraíma' },
                { nameShort: 'SC', name: 'Santa Catarina' },
                { nameShort: 'SP', name: 'São Paulo' },
                { nameShort: 'SE', name: 'Sergipe' },
                { nameShort: 'TO', name: 'Tocantins' }]

export default states
