# Use an official Ruby runtime as a parent image
FROM ruby:3.0.0

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  postgresql-client \
  && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get install -y nodejs \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install --global yarn

# Set an environment variable to store where the app will live inside the Docker image
ENV APP_HOME /app

# Create the application directory
RUN mkdir $APP_HOME

# Set the working directory
WORKDIR $APP_HOME

# Install Ruby dependencies
COPY Gemfile $APP_HOME/Gemfile
COPY Gemfile.lock $APP_HOME/Gemfile.lock
RUN bundle install

# Install JavaScript dependencies
COPY package.json $APP_HOME/package.json
COPY yarn.lock $APP_HOME/yarn.lock
RUN yarn install --check-files

# Copy the application files to the app directory
COPY . $APP_HOME

# Expose port 3000 and start the application
EXPOSE 3000
